import os

import regulAS

from setuptools import setup


setup(
    name='regulAS',
    version=regulAS.__version__,
    packages=['regulAS', 'regulAS.core', 'regulAS.utils', 'regulAS.reports', 'regulAS.persistence'],
    package_data={'': [os.path.join('conf', '*.yaml')]},
    url='https://github.com/slipnitskaya/regulAS',
    author='Sofya Lipnitskaya',
    author_email='lipnitskaya.sofya@gmail.com',
    description='regulAS is a bioinformatics package designed to assist researchers in identifying prospective '
                'regulators of alternative splicing events using large-scale RNA-Seq datasets from multiple omics '
                'data sources. Its core functionality offers automation of data processing, machine learning '
                'experiments, as well as efficient storage and processing of obtained results. '
                'With basic modules that integrate data retrieval of tumor and healthy samples generated by '
                'TCGA (https://www.cancer.gov/tcga) and GTEx (https://gtexportal.org/home) projects, predictive '
                'modelling and feature ranking capabilities, along with flexible report generation in tabular and '
                'visual forms, regulAS provides a comprehensive suite of tools for streamlined data exploration and '
                'research workflows. Additionally, regulAS supports flexible experiment configuration through YAML '
                'files, allowing users to easily adapt the package to their specific needs. One of the standout '
                'feature of regulAS is its extensibility, enabling end-users to expand its functionality by writing '
                'custom modules in Python. Discover the versatility of regulAS for your computational biology and '
                'bioinformatics research.',
    python_requires='>=3.7',
    install_requires=[
        'networkx==2.5',
        'numpy==1.19.2',
        'scipy==1.7.1',
        'scikit-learn==0.24.2',
        'pandas==1.2.2',
        'matplotlib==3.1.3',
        'omegaconf==2.1.0',
        'hydra-core==1.1.0',
        'hydra-colorlog==1.1.0',
        'sqlalchemy==1.4.17',
        'msgpack==1.0.2',
        'msgpack-numpy==0.4.6.1',
        'requests==2.26.0',
        'pyensembl==1.9.1',
        'tqdm==4.46.0'
    ]
)
